### ISSUE TITLE
Doesn't support node 16 or 15 for that matter

### ISSUE THREAD

**Issue by ghost** [PotatoParser/ffmpeg-cli#18]
```
npm ERR! code 1
npm ERR! path /home/tsukisuperior/Code/ffmpeg-cli/node_modules/lzma-native
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build && rimraf build
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/tsukisuperior/Code/ffmpeg-cli/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/home/tsukisuperior/Code/ffmpeg-cli/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@16.0.0-pre | linux | x64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/home/tsukisuperior/Code/ffmpeg-cli/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64/lzma_native.node" (not found)
npm ERR! node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-linux-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for lzma-native@6.0.1 and node@16.0.0-pre (node-v93 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error read ECONNRESET 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.0.0-pre | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.0.0-pre | linux | x64
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
npm ERR! gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:54:16)
npm ERR! gyp ERR! stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:440:10)
npm ERR! gyp ERR! stack     at Object.self.commands.<computed> [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:41:37)
npm ERR! gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:62:20)
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:29:7
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:78:11)
npm ERR! gyp ERR! System Linux 5.10.0-0.bpo.5-amd64
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/tsukisuperior/Code/ffmpeg-cli/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/home/tsukisuperior/Code/ffmpeg-cli/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /home/tsukisuperior/Code/ffmpeg-cli/node_modules/lzma-native
npm ERR! gyp ERR! node -v v16.0.0-pre
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/tsukisuperior/Code/ffmpeg-cli/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/home/tsukisuperior/Code/ffmpeg-cli/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/tsukisuperior/Code/ffmpeg-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Linux 5.10.0-0.bpo.5-amd64
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/home/tsukisuperior/Code/ffmpeg-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/tsukisuperior/Code/ffmpeg-cli/node_modules/lzma-native
npm ERR! node-pre-gyp ERR! node -v v16.0.0-pre
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tsukisuperior/.npm/_logs/2021-04-18T14_17_22_232Z-debug.log
```

**Comment by PotatoParser** [comment]
Thanks for the heads up! I've updated the dependencies (`a8a93f4`), currently, I've tested this on NodeJS v15.12. Let me know if the issue still persists!
